runtime: python
env: flex
entrypoint: gunicorn -b :$PORT main:app
threadsafe: true

runtime_config:
  python_version: 3

env_variables:
    SQLALCHEMY_DATABASE_URI: >-
      mysql+pymysql://root:mysecurepassword@/gotitdb?unix_socket=/cloudsql/gotit-160017:us-central1:gotit

beta_settings:
    cloud_sql_instances: gotit-160017:us-central1:gotit
